title: The Grant Smith Project
description: A site to hold some of my things.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
baseurl: /gsmithapps
url: https://gsmithapps.github.io