title: Grant Smith
description: A portfolio/resume etc.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
baseurl: "/GSmithApps" # the subpath of your site, e.g., /blog
url: "https://gsmithapps.github.io" # the base hostname & protocol for your site
